name: cache_initiated_query_rebuild
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  graphql_flutter:
    path: ../../packages/graphql_flutter
  graphql:
    path: ../../packages/graphql

flutter:
  uses-material-design: true
